---
apiVersion: v1
kind: Secret
metadata:
  name: concourse-worker-secrets
  namespace: concourse
type: Opaque
data:
  tsa_host_key.pub: <insert_your_base64_encoded_pub_key_here>
  worker_key: <insert_your_base64_encoded_key_here>
  worker_key.pub: <insert_your_base64_encoded_pub_key_here>
