apiVersion: v1
kind: Service
metadata:
  name: concourse-web
  namespace: concourse
spec:
  ports:
  - name: "concourse-web"
    protocol: "TCP"
    port: 8080
    targetPort: 8080
    nodePort: 30080
  - name: "concourse-tsa"
    protocol: "TCP"
    port: 2222
    targetPort: 2222
  selector:
    service: concourse-web
  type: NodePort
