apiVersion: v1
kind: Service
metadata:
  name: concourse-db
  namespace: concourse
spec:
  ports: 
  - name: postgres-db
    protocol: "TCP"
    port: 5432
    targetPort: 5432
  selector:
    service: concourse-db
  type: NodePort