---
apiVersion: v1
kind: Secret
metadata:
  name: concourse-web-secrets
  namespace: concourse
type: Opaque
data:
  authorized_worker_keys: <insert_your_base64_encoded_key_here>
  session_signing_key: <insert_your_base64_encoded_key_here>
  session_signing_key.pub: <insert_your_base64_encoded_pub_key_here>
  tsa_host_key: <insert_your_base64_key_here>
  tsa_host_key.pub: <insert_your_base64_encoded_pub_key_here>
